title: "Jiajie Shi"
description: "Research in ML, social networks, graphs, and other fun stuffs"
theme: jekyll-theme-cayman

repository: sjjgh/sjjgh.github.io

# (optional) enable markdown features
markdown: kramdown
kramdown:
  math_engine: mathjax

sass:
  style: expanded
