title: "Jiajie Shi"
description: "Research in Graph ML, Hyperbolic Geometry, and Biological Modeling"
theme: jekyll-theme-cayman

repository: sjjgh/sjjgh.github.io

# (optional) enable markdown features
markdown: kramdown
kramdown:
  math_engine: mathjax

sass:
  style: expanded
